spring:
  application:
    name: blog-server
  profiles:
    active: prod
  mvc:
    throw-exception-if-no-handler-found: true
  ####是否为工程中的资源文件建立映射
  resources:
      add-mappings: false

server:
  port: 31091
  servlet:
    context-path: /blog-server

###站点介绍
site:
  introduction: "万事从未风过耳，一生只是梦游身"


